Quicktext hu (magyar - Hungarian) translation
thundernest/quicktext pull request #37
Opened 2018-10-23 22:50 UTC by ovari

2018-10-24 11:58 UTC, jobisoft requested changes
Please undo changes not related to hu translation

2018-10-24 11:58 UTC, jobisoft commented on install.rdf
> -    <em:description>Adds a toolbar with unlimited number of text to quickly insert. It's also possible to use variables like [[TO=firstname]]. With settings for everything.</em:description>
Please undo this Change, not related to adding hu translation.

2018-10-24 12:00 UTC, jobisoft commented on install.rdf
> -    <em:description>Adds a toolbar with unlimited number of text to quickly insert. It's also possible to use variables like [[TO=firstname]]. With settings for everything.</em:description>
This is the original description from Emil, I would like to keep it for now

2018-10-24 12:01 UTC, jobisoft commented on install.rdf
> -    <em:description>Adds a toolbar with unlimited number of text to quickly insert. It's also possible to use variables like [[TO=firstname]]. With settings for everything.</em:description>
The fixes for URLs and links are ok, but I want to keep Emil's original description.

2018-10-24 13:10 UTC, ovari commented on install.rdf
> -    <em:description>Adds a toolbar with unlimited number of text to quickly insert. It's also possible to use variables like [[TO=firstname]]. With settings for everything.</em:description>
Should be done.

2018-10-24 13:11 UTC, ovari commented
Is it ready for to merge? Thank you

2018-10-24 14:23 UTC, jobisoft approved these changes

2018-10-24 14:23 UTC, merged

2018-10-24 14:23 UTC, jobisoft commented
Thanks!

2018-10-24 20:55 UTC, ovari commented
Does the version in the install.rdf need to be increased before uploading to [ATN](https://addons.thunderbird.net/hu/thunderbird/addon/quicktext/)?

2018-10-24 21:02 UTC, jobisoft commented
Sadly I cannot upload that new version to ATN. I will release one here on Github. The new version will not pass ATN review. The current version has passed review by grace and some stuff has to be changed before the next verison may be uploaded.

2018-10-24 21:04 UTC, ovari commented
Can you update https://addons.thunderbird.net/hu/thunderbird/addon/quicktext/ ?

2018-10-24 21:08 UTC, jobisoft commented
No I cannot, the current version will not pass review (done by ATN reviewers).

2018-10-24 21:10 UTC, ovari commented
We are talking about the description, summary, image captions, not the xpi file.

2018-10-24 21:13 UTC, jobisoft commented
yes, that I can do, wanna post it here?

2018-10-24 21:18 UTC, ovari commented
Please see:
https://github.com/thundernest/quicktext/pull/37#issuecomment-432824891

2018-10-24 21:42 UTC, jobisoft commented
That comment did not have that text in the initial version...

2018-10-24 21:45 UTC, jobisoft commented
Done

2018-10-25 04:53 UTC, ovari commented
Sorry and thank you!