Fixing some PRO tags
thundernest/quicktext pull request #6
Opened 2018-05-13 21:56 UTC by jobisoft

2018-05-14 21:22 UTC, jobisoft commented
I think the Pro version is fixed now as well and I prepared everything for the "switch". If this PR gets accepted, I will send this version to AMO for review. 

The "Pro" branch should be set as default, after this PR has been accepted.

2018-05-15 17:44 UTC, lieser requested changes
Nice to see that you got also the pro version to run again.

Changes looks good, just 2 unused variables I think.

2018-05-15 17:44 UTC, lieser commented on chrome/content/quicktext.js
> +      var fileHandler = ioService.getProtocolHandler("file").QueryInterface(Components.interfaces.nsIFileProtocolHandler);
Is `fileHandler` (an wherefore also `ioService`) used anywhere?

2018-05-15 18:43 UTC, jobisoft commented
Removed. They are not used anywhere else.

2018-05-15 21:11 UTC, lieser approved these changes

2018-05-15 21:11 UTC, merged

2018-05-15 21:19 UTC, lieser commented
Thanks again for you effort.

I think it would be good to start tagging the releases, So please let me now from which commit you will do the release (i assume it will be the 5ab56cdbd0764d7c28e216b199d241bf868fed3d, just want to make sure)

2018-05-15 21:49 UTC, jobisoft commented
I usually keep the github releases in sync with the AMO releases and I think the AMO review will ask for more changes. So the current 0.9.14 will not be final. My plan is to fix the AMO issues and than release v1.0 - which can also be tagged/released on github. 

Would you like to tag/release 0.9.12? The current official version?

If you ask me, I would start tagging with v1.0 ...